### PR TITLE
Fix encoding of negative arbitrary-precision integers

### LINKED ISSUE #161: Fix encoding of negative arbitrary-precision integers
There is a bug in the code generated for encoding of negative arbitrary-precision integers where the generated code attempts to compute the logarithm of a negative number.

### PR DESCRIPTION
**Pull request by theo25**
Fixes #161

### CODE REVIEW

File: libsolidity/codegen/IeleCompiler.cpp [hunk 1]
```diff
@@ -2143,12 +2143,41 @@ void IeleCompiler::appendByteWidth(iele::IeleLocalVariable *Result, iele::IeleVa
...
+      appendConditional(IsPositiveValue, PositiveResults,
+       [&Value, this](llvm::SmallVectorImpl<IeleRValue *> &Results){
+        Results.push_back(IeleRValue::Create({Value}));
+       },
+       [&Value, this](llvm::SmallVectorImpl<IeleRValue *> &Results){
+         iele::IeleLocalVariable *PositiveResult =
+           iele::IeleLocalVariable::Create(
+             &Context, "positive.value", CompilingFunction);
+        iele::IeleInstruction::CreateBinOp(
+          iele::IeleInstruction::Sub, PositiveResult,
```
Comment (dwightguth) [inline libsolidity/codegen/IeleCompiler.cpp]: Pretty sure this should be a bitwise not. You could also adjust for twos complement by replacing 0 with -1, but not showing use less gas.
